export enum estadoPostulacion {
    POSTULACION_EN_CURSO = 'POSTULACION_EN_CURSO',
    POSTULACION_EN_ESPERA = 'POSTULACION_EN_ESPERA',
    POSTULACION_APROBADA = 'POSTULACION_APROBADA',
    POSTULACION_RECHAZADA = 'POSTULACION_RECHAZADA',
    POSTULACION_BORRADOR = 'POSTULACION_BORRADOR'
}