export enum EstadoPropuesta{
    PROPUESTA_BORRADOR		    =	"PROPUESTA_BORRADOR",
	PROPUESTA_SIN_ASIGNAR	    =	"PROPUESTA_SIN_ASIGNAR",	
	PROPUESTA_ESPERA    		=	"PROPUESTA_ESPERA",
	PROPUESTA_APROBADA  		=	"PROPUESTA_APROBADA",	
	PROPUESTA_OBSERVADA 		=	"PROPUESTA_OBSERVADA",	
	PROPUESTA_CANCELADA 		=	"PROPUESTA_CANCELADA"
}